- .travis.yml
- package-lock.json
- package.json
- script/seed.spec.js
- server/api/users.spec.js
- server/auth/google.js
- server/db/models/category.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/products-ordered.js
- server/db/models/user.js
- server/db/models/user.spec.js
> Model definitions

- server/api/cart.js
- server/api/category.js
- server/api/homepage.js
- server/api/index.js
- server/api/product.js
- server/api/users.js
> added the routes

- script/seed.js
- server/api/category.js
- server/db/db.js
- server/db/models/category.js
- server/db/models/product.js
> Creating dummy data

- client/components/products.js
- client/store/products.js
- server/db/models/ordered-products.js
- server/db/models/product.js
> React component setup

- client/components/products.js
- client/routes.js
- public/style.css
> edited product component and product routes

- client/components/categories.js
- client/components/single-product.js
- client/store/categories.js
- client/store/index.js
- client/store/singleProduct.js
> added singleProduct and allCategories component

- client/components/featured-products.js
- client/components/navbar.js
- client/components/products.js
- client/routes.js
- client/store/products.js
- script/seed.js
- server/api/products.js
> Product featuredproduct components

- client/components/featured-products.js
- public/style.css
- script/seed.js
> added 1 order to seed file

- client/components/auth-form.js
- client/components/navbar.js
- client/components/order-history.js
- client/routes.js
- client/store/index.js
- client/store/order-history.js
- public/style.css
- server/api/index.js
- server/auth/google.js
- server/auth/index.js
- server/db/models/ordered-products.js
- server/index.js
> oauth works and orderhistory displays order data

- client/components/order-history.js
- server/api/orderHistory.js
> got orderhistory page working

- client/components/auth-form.js
- client/components/categories.js
- client/components/createUser.js
- client/components/index.js
- client/components/order-history.js
- client/components/signUpForm.js
- client/routes.js
- client/store/user.js
- public/style.css
- script/seed.js
- server/api/users.js
- server/db/models/user.js
> Kcho added Sign up feature

- client/components/auth-form.js
- client/components/categories.js
- client/components/featured-products.js
- client/components/navbar.js
- client/components/order-history.js
- client/components/products.js
- client/components/single-product.js
- client/routes.js
- client/store/singleProduct.js
- package-lock.json
- package.json
- public/index.html
- public/style.css
- script/seed.js
- server/api/cart.js
- server/api/index.js
- server/api/orderedProducts.js
- server/db/models/index.js
- server/db/models/ordered-products.js
- server/db/models/product.js
- server/db/models/user.js
> Implement semantic ui

- client/components/auth-form.js
> fix oauth href issue on auth-form.js

- client/components/auth-form.js
- client/components/cart.js
- client/components/single-product.js
- client/store/cart.js
> cart multiplies by quantity

- client/components/index.js
- client/components/thank-you.js
- client/routes.js
> thank you for your orger component

- client/components/cart-guest.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
> separate cart routes and components for logged in and guest users

- client/components/cart.js
- client/components/paymentForm.js
- client/store/cart.js
- server/api/cart.js
> K cho checkout button

- client/components/cart-guest.js
- client/components/cart.js
- client/components/home.js
- client/components/navbar.js
- client/components/single-product.js
- client/routes.js
> Stable build

- client/components/cart-guest.js
- client/components/guest-checkout-entry.js
- client/components/guest-checkout-form.js
- client/components/index.js
- client/components/navbar.js
- client/store/cart.js
- client/store/guest-user.js
- client/store/index.js
- client/store/order-history.js
- client/store/singleProduct.js
- client/store/user.js
- server/api/cart.js
- server/api/users.js
> Makes guest checkout function

- client/components/cart-guest.js
- client/components/cart.js
> alerts user that cart is empty when checkout is clicked.

- client/components/api-warning.js
- client/components/cart-guest.js
- client/components/cart.js
- client/components/featured-products.js
- client/components/index.js
- client/components/navbar.js
- client/components/order-history.js
- client/components/products.js
- client/components/thank-you.js
- client/routes.js
- public/style.css
- server/api/index.js
> order history now renders extended price and order total for each order

- server/api/users.js
> protect user routes

- client/components/cart.js
- server/api/users.js
> fixed api protection on user route bug

- client/components/cart-guest.js
- client/components/cart.js
- client/components/order-history.js
> order total decimal bug fix
